sudo: false
language: python
python:
#    - 3.6
    - 3.7-dev
#    - 3.8-dev
install:
    - pip install --upgrade setuptools
    - pip install --upgrade wheel
    - pip install --upgrade twine
script:
    - python3 setup.py -q install
    - python3 setup.py sdist bdist_wheel
deploy:
    provider: pypi
    user: holzkohlengrill
    # Do not use git Bash on Windows since encryption will fail
    password:
        secure: Uo5jQ41EPGPMQkDCK3a/2IFzj4Ag/XbtW/7r6rqsj1oxhxa57GkoLHBhpHaSNfdp5K+HW+TiMtcmDAk92Hb8um+6jVDXjFNzhyS4Sy75UetzEQUe7Z8YlUXDaLLcEtczrBwv9RrCkJPROV7MJ2n9JhwuZVBjcV6X/V0Ru+RrkN7dcb4srtG+1qkfjiyGx0MxjgK/WqIGjY44S4a9hK/+kGm7clthHqEnS4rhOLyvzPyHsFhDHcn810/c9iOl18RpFHc0ND7q6s4/LRSAY+NMWh4erQO3UoiCatjsGfZ7kkbsCo0XtZEBMRzU8E4DyHLLwK3syEUz/lrdufcDTwBr/AVoFnlteQnyPWlICCeBETK+OvxPQC6o1bhGgdW75WFVlQ8naKdcJ4gJxeKb0h/GWUujKGtRnEZdDk1ZLhQ39yiITrGsLrDweqKbtfanjTdun7zxqZQTNFjmfnowwtWqZDQtbWPrW6Kx0Buk5TD+wBMvwg5iRDlMyGR3UEGWPHU9LUwD0ra6bjJEFJeUxSAmGkYz4aFg5/IGJs8g/V7OA3dTdijGYpuWL/PgLqhTMkivjSsTgS124aKQWBXIRRN+FFyih51eROPnwgE0YWVmHkPvZT2gTD4Ca0c8Z+VsJhJQXBYamgmNADEHk5G+Di1Q9fKudJINtgT/e2bO9zc7bTg=
    on:
        # deploy only on tags
        tags: true

