sudo: false
language: python
python:
- 3.6
- 3.7-dev
install:
- pip install --upgrade setuptools
- pip install --upgrade wheel
- pip install --upgrade twine
script:
- python3 setup.py -q install
- python3 setup.py sdist bdist_wheel
deploy:
  provider: pypi
  user: holzkohlengrill
  password:
    secure: XKUyQgL1B8j669l6wJM1gEpsRo+RAlRji88sQChebzW4EPFhk4imOx2b8U7KZIPHHBpeZ6b27MHCjlpzCVirJGkcDPcJdoehJdoJDZvezKjdHL6Sm6HbnSh2q9DoWepaMhq1ZBGbHxQ0kSIKHuq/XgElZlW/aE7Uh4iOJAwC+BrMF9T7kqsVRKY2MX+YxZhJjjLrsd13D/C/ZtM1IdwwLTW89qd43onBKLr+19wRGBuAI+Jz+OCmNg3vl6p/uAno8qOML/Roxvl6oRHdCwZXxwbWjqQJ2zmT69izzWJaAwEX6LikFIc9FmiCfQsRDgRffbCTCR9KsUNN6/OXP/DMyXLfc8wRXfjndOLtiJ1QErrTSZWCmXUdJglW5o7iM9Z67Eb0mVR1dqujDuYlqmyQigK9g5fX43T8D60Kz7Ldx10nW4YskckfkzNXMwkuSTn/5iL+Nyl9t3idyO8gVCCxGoNJA3ZytxPOBbPXpOlR92tWCj6uZ582MQ/VEUrQfRASzDg8HE1IKLuc6VUmU12PhfkN73EC0hZCghOKAzgjxfgT8MEfLPu9xSmo0/2uftfevOV+y4QjUui9RE7rjPptdfpqOBv2BNX4IXPPQbq6k57WDD/RUBQmGcU0MrzhstRKlTtA5W9sWq9pCJh6AVJMXeZa/kpwe3wznHwSRLq6nfY=
