sudo: false
language: python
python:
- 3.6
- 3.7-dev
#- 3.8-dev
install:
- pip install --upgrade setuptools
- pip install --upgrade wheel
- pip install --upgrade twine
script:
- python3 setup.py -q install
- python3 setup.py sdist bdist_wheel
deploy:
  provider: pypi
  user: holzkohlengrill
  password:
    secure: oWWQg4c1Lb4kdpAV2le/y4bXQbdPVRVQ0VPr6CbXvRmeQC3lnVHorAylG2eevRmPnqnBMMTlN6LJCJAh+T7ewpTEAXKaaV94RQUxzMJquTV7a378uaKj/RUZFQ9ITkPtj9WjqVR3S470MFL3Oxc5KrqQPlMSwyaL0jOcXXleXBM1Mjao4TEEvgrhnwB0K5d8OPrJoxKbgVn6xGCzbJP+XB46A/iRr41DQwo7+m3Xy/9igouFwSqKZElHLrmDHtTWKwBYRft/y/KrXvx75j7T5eB8rx0FopzfiD8bQcG3G92kSwfwYS4zkNSUV/o9zRtu2QSAsUQY0ruoR3r0udNwPeVbPLKJ3OV8ffDxdg/gQbxXd7LF8cEPs2ENS4k6kSSbCvEbMLaROMpdWNr0krRp4gBzpZYicLuLnZpOe1QYdY2wBmC4oizu6yQOAPPVSnAW3aLAhitBscmk1A1zu2stgKiPy00Fy2a2vY2DxWQ4Bag9IH/bcriesx+Biqa7D2EPF9ldzB1tbqKjn7PFjEIsUmrnovQLuAPsT7YB9Cuk5p3q+wtLKsVjJvpPnB4Dx/UAoFDR++YAvrdwNgKt2aJ781l5340xRFYZ4fBhGL+OgoFS89KPUxGfQGBRzbx+r16m8H04jRINwNJUc/aBnTgxq8NaBIl0ZTo/txIPvPodD4g=
#  on:
    # deploy only on tags
#    tags: true
