sudo: false
language: python
python:
- 3.7-dev
install:
- pip install --upgrade setuptools
- pip install --upgrade wheel
- pip install --upgrade twine
script:
- python3 setup.py -q install
- python3 setup.py sdist bdist_wheel
deploy:
  provider: pypi
  user: holzkohlengrill
  password:
    secure: $PYPI_SECRET
  on:
    tags: true
