sudo: false
language: python
python:
- 3.7-dev
install:
- pip install --upgrade setuptools
- pip install --upgrade wheel
- pip install --upgrade twine
script:
- python3 setup.py -q install
- python3 setup.py sdist bdist_wheel
deploy:
  provider: pypi
  user: holzkohlengrill
  password:
    secure: uN0lbq5Jdk1LeqeltG4Zmq3CPkCV6ryj3y8v/VD/f5JSgZc9igApbuyooa0cX29S6+X7w0Fsn6dQkXyf+j2/uYcrG55ez7KKjf2XnpiWOnESvq6rh/I7Ta4h/K3P+b+hHt1bjfIcrSDpO0fuBqlX1PxKcdIHdwkWCM3BKA7sDvbDjvDhT+/pnlXUiysiAJ0AdGig7MBDiFhRj4/8aAP+ZZnfxJIODiYYXesnOrkiMiF6yGm34Q4MBSKkbQD3GHrHDZxVwN9luoToLEKnKyxiqVZXUFRg4mwVHqxgdTSDa6yC06IUCpGDLD3mQB0w3Jh0Ai2uS0pmTaBE9BWE2ERvLvuuzW2guUzyHm5G2wRtVtCVD1wRTd7t06oNfrXLgPxH0aUOPo4SvWTUawFqu3JKRiVm9UvqDpkjpaGYdAGW+4OuOJlcsejzi3jOnU22j7EkFDVyYlijGmseGL6HkbCOT+7fso0H7sOZQkcJgJRTuwQgVooFV2l+kX9N8SMeFPKnGgWZYG5sVDLmxMiM6p9GMPLJ3yNqsMIWEIzPojud08jnGl+MiIxm+ibsrBqURHkMCD49eRx/zwr4nBbh4KzPhc9eH89+Acujz4LSzZ3L2pwyNkga430jNtMSGeMvLV0cPdJyeHDPV1rDTgxnbrkB4FdBXwclRTUatAXENIVU0SU=
  on:
    tags: true
