sudo: false
language: python
python:
- 3.7-dev
install:
- pip install --upgrade setuptools
- pip install --upgrade wheel
- pip install --upgrade twine
script:
- python3 setup.py -q install
- python3 setup.py sdist bdist_wheel
deploy:
  provider: pypi
  user: holzkohlengrill
  password:
    secure: G5RkhrqxaPkpZtVxzLv9Sa0jZL7rD8WBKJ3vz/vWsLsVySgNSy1ivdDLR7TVSGAAi/PViIgx1398nq15SJ3NXFR0d/8KcGtJJLrYLZRUmU1ZU7tkKaO/qVtgIhH3HS2l/GVatmoabtRxYf8GFAuRiL+T1kLZKJKVykWFdaleETVIeJRSFg4iDaYsKZOVtm+lt1l08Lcw3uoyPrvp+CQ1858XlQd9i5+sKDm5vwvB0UED0l0spKIXKB+a1RGsDfLYOUN8nYKC2SrPVKlzANp1KSzAWLI2l+KlqaiEy7cYKvZphtbWnzCLyyVBMPKzLgthAXicCDFvcKRs43HNsfLl6MXjWX6fKYWUA3SeuJWP6ho+39mudT3zR4ZokM7UU3C40tAmdQXaC0bIHcrv9VWSwshfGVI3jZziIOJejCOsFZ97RHO5E/85Tmd7q8ArAMnf/64UqSyHpJcPALFjxR1FJGc8npurJ1CDXGDwVjbisyZ/+8N6jlia+OG+pI4JF6L/78r5A4u3vaaVachGGP5QKFX1og2zOR2cqUPpkuKC/iRcWxF0do5W/rPy7heF8Va7rA6yYna/0eewBddaJ+em47GiJo/iHAiLOcyaU7+tZBkwQaIBAW8d2gwkA2YUNjGUnSnb8d27Ibk2tPeYoymzXXwXQso3oKeLhJyPt0ieNOw=
  on:
    tags: true
