sudo: false
language: python
python:
- '3.3'
- '3.4'
- '3.5'
- '3.6'
- 3.7-dev
- 3.8-dev
script:
- python3 -m test_Scout.py
- python setup.py -q install
deploy:
  provider: pypi
  user: holzkohlengrill-Builder
  password:
    secure: dRvXhn4z9yPts9ByJLYFKQna+XYd/KmGsFyEvVFmYGO88OoQW0tgO3I2841e+1sZdUBDWtiaj52b4JuQU68cxdvcfuDHgU1Jrwt7/lQfRs9N4V375K9AcUPkvCEfQcRwJkNzIIqh4c7oKsS9GL/mZh0Bk4x7Div0414MNY+memaMrFLTqvqVgx51mDb7OF/TnButg9CmLew32rQlRlWDDk/cY2BTCZ1BFQxtjMPOKpjvQD3YXuoDbhHbXd+x2dJ9eTTm5gFAh4ohTwFewYSfHFMBbpDsp1PkdeeGqIOt9POQJWvOIH8M2T1DGbD2SLjAATLbqCvnoBmXckBqYYGik5/Djb3IVwNEnBPMhsU1tMlWQaJ0ItrZgFWvUtiA4HsTMHOQPLbCb9mQRhdjl68pr9lCLG/DWpYoI7HIR4yrga16N+rdycJb75LGdarFNdwVQLa0zwEhkQy3MuF1S2zXo0fFLg6QkrCiDUMoXVyZyu1F9EEm/BbSPJkqdyy/fyqDGTV1h7pRaXKvDlbuQznxCHPiHw2RpBFd9UWCli0Q6lA+GsDmpx5Vruc9wP0fOHiDBfoFjvQwiMw0/8DcDpmGg3Uw50TOZwecB/6/PvYncn8audewBBm72VtFSd4gfXfegM6bLNAijNMZ6tD9EAizIz6S07GOri9v6raLvVukFd4=
  on:
    tags: true

